# Generated by Django 4.1.7 on 2023-02-27 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_employee_price_registerrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerrequest',
            name='phone',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
