# Generated by Django 4.1.7 on 2023-03-20 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_city_medicalcenter_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerrequest',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='register_request', to='main.city'),
        ),
    ]
