# Generated by Django 4.1.7 on 2023-04-05 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_registerrequest_register_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerrequest',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='registerrequest',
            name='register_at',
            field=models.DateField(),
        ),
    ]
